#pragma once 

#include "asset/asset_manager.hpp"
#include "asset/loader.hpp"

#include "components/camera.hpp"
#include "components/geometry.hpp"
#include "components/transform.hpp"

#include "core/clock.hpp"
#include "core/config.hpp"
#include "core/container.hpp"
#include "core/enum.hpp"
#include "core/exception.hpp"
#include "core/fnv1a.hpp"
#include "core/format.hpp"
#include "core/json_fwd.hpp"
#include "core/json.hpp"
#include "core/meta.hpp"
#include "core/span.hpp"
#include "core/type_info.hpp"
#include "core/uuid.hpp"

#include "engine/builder.hpp"
#include "engine/game.hpp"

#include "entity/entity.hpp"
#include "entity/system.hpp"

#include "graphics/blend_state.hpp"
#include "graphics/buffer_type.hpp"
#include "graphics/buffer.hpp"
#include "graphics/builtin_shaders.hpp"
#include "graphics/color.hpp"
#include "graphics/graphics_device.hpp"
#include "graphics/image_format.hpp"
#include "graphics/image.hpp"
#include "graphics/material.hpp"
#include "graphics/mesh.hpp"
#include "graphics/shader.hpp"
#include "graphics/texture_cube_face.hpp"
#include "graphics/texture_cube.hpp"
#include "graphics/texture_filter.hpp"
#include "graphics/texture_format.hpp"
#include "graphics/texture_wrap.hpp"
#include "graphics/texture.hpp"
#include "graphics/topology.hpp"
#include "graphics/vertex_attribute.hpp"
#include "graphics/vertex_desc.hpp"
#include "graphics/vertex_element.hpp"
#include "graphics/vertex_format.hpp"

#include "input/gamepad_axis.hpp"
#include "input/gamepad_button.hpp"
#include "input/gamepad.hpp"
#include "input/keyboard.hpp"
#include "input/keycode.hpp"
#include "input/mouse_button.hpp"
#include "input/mouse.hpp"

#include "loaders/mesh_loader.hpp"
#include "loaders/texture_cube_loader.hpp"
#include "loaders/texture_loader.hpp"

#include "math/easing.hpp"
#include "math/mat4.hpp"
#include "math/math.hpp"
#include "math/vec2.hpp"
#include "math/vec3.hpp"
#include "math/vec4.hpp"

#include "platform/window.hpp"

#include "systems/renderer.hpp"
